### ISSUE TITLE
Reddit2kindle no longer sending files to my address.

### ISSUE THREAD

**Issue by Janp8** [JamieMagee/reddit2kindle#56]
Please can you help in this?

**Comment by DianaAnton** [comment]
I also seem to have this problem. I have both _convert@reddit2kindle.com_ and _@reddit2kindle.com_  added to my email list and I am not able to send nosleep posts to my kindle.

I have tried using the kindle address and the address for my phone app from different browsers and devices with no luck

**Comment by JamieMagee** [comment]
It looks like reddit is blocking my API access. I can see the following exception:

```
Result: Function 'PostQueue', Invocation id 'aa99efa5-85c6-448f-8ce5-10cfaa086aeb': An exception was thrown by the invocation.
Exception: System.AggregateException: One or more errors occurred. (Reddit API returned Unauthorized (401) response.)
 ---> Reddit.Exceptions.RedditUnauthorizedException: Reddit API returned Unauthorized (401) response.
   at Reddit.Models.Internal.Request.ProcessResponse(IRestResponse res)
   at Reddit.Models.Internal.Request.ExecuteRequest(RestRequest restRequest)
   at Reddit.Models.LinksAndComments.Info(String id, String subreddit, Boolean loadReplies)
   at Reddit.Controllers.Post.Info()
   at Reddit.Controllers.Post.About()
   at Reddit2Kindle.Functions.Services.RedditService.GetPost(String uri) in D:\a\reddit2kindle\reddit2kindle\src\Reddit2Kindle.Functions\Services\RedditService.cs:line 23
   at Reddit2Kindle.Functions.Services.Reddit2KindleService.SendPostAsync(PostRequest request) in D:\a\reddit2kindle\reddit2kindle\src\Reddit2Kindle.Functions\Services\Reddit2KindleService.cs:line 26
   at Reddit2Kindle.Functions.Functions.QueueFunction.PostAsync(PostRequest request) in D:\a\reddit2kindle\reddit2kindle\src\Reddit2Kindle.Functions\Functions\QueueFunction.cs:line 25
   at Microsoft.Azure.Functions.Worker.Invocation.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\VoidTaskMethodInvoker.cs:line 22
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
   at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
   at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
Stack:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
   at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
   at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
```

**Comment by Janp8** [comment]
Ohh Yes! this is due to Reddit's latest policy of blocking 3rd Party Apps from accessing its content: 
https://www.reddit.com/r/Android/comments/15qunao/reddit_is_reportedly_suspending_users_for_using/.

Here is a way to resume access suggested by a user: 
https://www.reddit.com/r/Android/comments/14zl0vh/use_3rd_party_reddit_apps_again/

**Comment by Janp8** [comment]
Hi, thank you very much for looking into it on my request. Please let me know if the issue has been resolved.

**Comment by JamieMagee** [comment]
Unfortunately I don't have the capacity to maintain this project anymore. I created reddit2kindle for myself almost a decade ago, but I haven't used it in years.
